# Generated by Django 3.0.2 on 2021-04-23 00:08

from django.db import migrations, models

def load_scope(apps, schema_editor):
    Scope = apps.get_model("oidc_provider", "Scope")
    OpenID_Scope = Scope(scope="openid", description="openid")
    OpenID_Scope.save()
    Profile_Scope = Scope(scope="profile", description="profile")
    Profile_Scope.save()
    Email_Scope = Scope(scope="email", description="email")
    Email_Scope.save()
    Address_Scope = Scope(scope="address", description="address")
    Address_Scope.save()
    Phone_Scope = Scope(scope="phone", description="phone")
    Phone_Scope.save()
    Offline_Scope = Scope(scope="offline_access", description="offline_access")
    Offline_Scope.save()


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_add_scope_20210423_0008'),
    ]

    operations = [
        migrations.RunPython(load_scope),
    ]
