# Generated by Django 3.2.7 on 2022-04-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0028_add_default_scope_20210503_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jwt_alg_at',
            field=models.CharField(choices=[('Opaque', 'None'), ('HS256', 'HS256'), ('RS256', 'RS256')], default='RS256', help_text='Algorithm used to encode Access Tokens.', max_length=10, verbose_name='Access Token JWT Algorithm'),
        ),
    ]
