# Generated by Django 3.2.7 on 2022-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_client_jwt_alg_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWKKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('key_type', models.CharField(choices=[('RS256', 'RSASSA-PKCS-v1_5 using SHA-256'), ('RS384', 'RSASSA-PKCS-v1_5 using SHA-384'), ('RS512', 'RSASSA-PKCS-v1_5 using SHA-512'), ('ES256', 'ECDSA using P-256 and SHA-256'), ('ES384', 'ECDSA using P-384 and SHA-384'), ('ES512', 'ECDSA using P-521 and SHA-512'), ('PS256', 'RSASSA-PSS using SHA-256 and MGF1 with SHA-256'), ('PS384', 'RSASSA-PSS using SHA-384 and MGF1 with SHA-384'), ('PS512', 'RSASSA-PSS using SHA-512 and MGF1 with SHA-512')], default='ES256', help_text='Specifies the cryptographic asymetric algorithms to sign the JWT Tokens', max_length=30, verbose_name='Key Type')),
                ('key', models.TextField(help_text='Paste your private Key here.', verbose_name='Key')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('expired', models.BooleanField(default=False, verbose_name='Is Expired?')),
            ],
            options={
                'verbose_name': 'JWK Key',
                'verbose_name_plural': 'JWK Keys',
            },
        ),
        migrations.DeleteModel(
            name='RSAKey',
        ),
    ]
