# Generated by Django 4.2.11 on 2024-12-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_alter_client_owner_alter_client_response_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientapi', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='token',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientapi', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientapi', verbose_name='Client'),
        ),
    ]
