# Generated by Django 3.2.7 on 2022-04-19 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0030_auto_20220419_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwkkey',
            name='expired',
        ),
        migrations.AlterField(
            model_name='jwkkey',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From'),
        ),
    ]
