# Generated by Django 3.2.7 on 2022-04-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0031_auto_20220419_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwkkey',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='jwkkey',
            name='key',
            field=models.TextField(blank=True, help_text='Paste your private Key here.', verbose_name='Key'),
        ),
    ]
