# Generated by Django 3.2.7 on 2022-06-16 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0034_auto_20220516_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWEKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('key_type', models.CharField(choices=[('OCT128', '(OCT128) 128 bit symmetric key'), ('OCT256', '(OCT256) 256 bit symmetric key'), ('OCT384', '(OCT384) 384 bit symmetric key'), ('OCT512', '(OCT512) 512 bit symmetric key'), ('RSA2048', '(RSA2048) RSA 2048 bits'), ('RSA3072', '(RSA3072) RSA 3072 bits'), ('RSA4096', '(RSA4096) RSA 4096 bits'), ('EC256', '(EC256) Elliptic Curve using P-256'), ('EC384', '(EC384) Elliptic Curve using P-384'), ('EC521', '(EC521) Elliptic Curve using P-521'), ('ECsecp256k1', '(ECsecp256k1) Elliptic Curve using secp256k1'), ('OKPEd25519', '(OKPEd25519) Edwards Curve using Ed25519'), ('OKPEd448', '(OKPEd448) Edwards Curve using Ed448'), ('OKPX25519', '(OKPX25519) Edwards Curve using X25519'), ('OKPX448', '(OKPX448) Edwards Curve using X448')], default='ES256', help_text='Specifies the cryptographic asymetric algorithms to sign the JWT Tokens', max_length=30, verbose_name='Key Type')),
                ('key', models.TextField(help_text='Paste your private Key here.', verbose_name='Key')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name': 'JWK Key',
                'verbose_name_plural': 'JWK Keys',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JWEPrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('key_type', models.CharField(choices=[('OCT128', '(OCT128) 128 bit symmetric key'), ('OCT256', '(OCT256) 256 bit symmetric key'), ('OCT384', '(OCT384) 384 bit symmetric key'), ('OCT512', '(OCT512) 512 bit symmetric key'), ('RSA2048', '(RSA2048) RSA 2048 bits'), ('RSA3072', '(RSA3072) RSA 3072 bits'), ('RSA4096', '(RSA4096) RSA 4096 bits'), ('EC256', '(EC256) Elliptic Curve using P-256'), ('EC384', '(EC384) Elliptic Curve using P-384'), ('EC521', '(EC521) Elliptic Curve using P-521'), ('ECsecp256k1', '(ECsecp256k1) Elliptic Curve using secp256k1'), ('OKPEd25519', '(OKPEd25519) Edwards Curve using Ed25519'), ('OKPEd448', '(OKPEd448) Edwards Curve using Ed448'), ('OKPX25519', '(OKPX25519) Edwards Curve using X25519'), ('OKPX448', '(OKPX448) Edwards Curve using X448')], default='ES256', help_text='Specifies the cryptographic asymetric algorithms to sign the JWT Tokens', max_length=30, verbose_name='Key Type')),
                ('key', models.TextField(help_text='Paste your private Key here.', verbose_name='Key')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name': 'JWK Key',
                'verbose_name_plural': 'JWK Keys',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JWSKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('key_type', models.CharField(choices=[('OCT128', '(OCT128) 128 bit symmetric key'), ('OCT256', '(OCT256) 256 bit symmetric key'), ('OCT384', '(OCT384) 384 bit symmetric key'), ('OCT512', '(OCT512) 512 bit symmetric key'), ('RSA2048', '(RSA2048) RSA 2048 bits'), ('RSA3072', '(RSA3072) RSA 3072 bits'), ('RSA4096', '(RSA4096) RSA 4096 bits'), ('EC256', '(EC256) Elliptic Curve using P-256'), ('EC384', '(EC384) Elliptic Curve using P-384'), ('EC521', '(EC521) Elliptic Curve using P-521'), ('ECsecp256k1', '(ECsecp256k1) Elliptic Curve using secp256k1'), ('OKPEd25519', '(OKPEd25519) Edwards Curve using Ed25519'), ('OKPEd448', '(OKPEd448) Edwards Curve using Ed448'), ('OKPX25519', '(OKPX25519) Edwards Curve using X25519'), ('OKPX448', '(OKPX448) Edwards Curve using X448')], default='ES256', help_text='Specifies the cryptographic asymetric algorithms to sign the JWT Tokens', max_length=30, verbose_name='Key Type')),
                ('key', models.TextField(help_text='Paste your private Key here.', verbose_name='Key')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name': 'JWK Key',
                'verbose_name_plural': 'JWK Keys',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='JWKKey',
        ),
        migrations.AlterField(
            model_name='client',
            name='at_jwe_enc',
            field=models.CharField(choices=[('A128CBC-HS256', 'AES_128_CBC_HMAC_SHA_256 authenticated encryption algorithm'), ('A192CBC-HS384', 'AES_192_CBC_HMAC_SHA_384 authenticated encryption algorithm'), ('A256CBC-HS512', 'AES_256_CBC_HMAC_SHA_512 authenticated encryption algorithm'), ('A128GCM', 'AES GCM using 128 bit key'), ('A192GCM', 'AES GCM using 192 bit key'), ('A256GCM', 'AES GCM using 256 bit key')], default=None, help_text='Algorithm used to encodeNoDataAllowedErr JWE Access Tokens.', max_length=13, null=True, verbose_name='JWE Algorithm to Encode'),
        ),
    ]
